name: Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Cypress tests and generate report
        run: npx cypress run --reporter mochawesome
      
      - name: Combine generate json files
        run: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
        
      - name: Generate HTML report
        run: npx marge mochawesome.json

      - run: ls & mkdir report & mv mochawesome.html report

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatório de testes de performance
          path: report

      - name: publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report