name: Pipeline CI

permissions: 
  contents: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Cypress tests and generate report
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --reporter mochawesome
      
      - name: Combine generate json files
        run: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
        
      - name: Generate HTML report
        run: npx marge mochawesome.json

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatório de testes de api
          path: mochawesome-report

      - name: publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: mochawesome-report